repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    files: ^backend/.*\.py$
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    files: ^backend/.*\.py$
    hooks:
      - id: isort

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    files: ^backend/.*\.py$
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    files: ^backend/.*\.py$
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    files: ^backend/.*\.py$
    hooks:
      - id: conventional-pre-commit
